stages:
  - build
  - test
  - security
  - production

default:
  image: bcleonard/generic-cicd-dockerdev-image:latest
  before_script:
  - echo "Running before_script"
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

syntax-check:
  stage: build
  script:
  - echo "running syntax check:"
  - flake8 --statistics

security-link-check:
  stage: build
  script:
  - echo "running security lint check:"
  - bandit -x ./virtualenv -r .

test-job1:
  stage: test
  script:
  - echo "This job tests something"
  - echo $PWD

test-job2:
  stage: test
  script:
  - echo "This job tests something, but takes more time than test-job1."
  - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
  - echo "which simulates a test that runs 20 seconds longer than test-job1"
  - echo $PWD
  - sleep 20

security-job1:
  stage: security
  script:
  - echo "running python pip-audit:"
  - echo $PWD
  - python3 -m venv ~/virtualenv/pip-audit
  - . ~/virtualenv/pip-audit/bin/activate
  - pip-audit -r requirements.txt
  - deactivate 

production-job1:
  stage: production
  script:
  - echo "running production push to github:"
  - echo $PWD
  - cat .git/config
  - git remote set-url github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_REPO.git
  - cat .git/config
  - echo "git remote remove github"
  - echo "git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_REPO.git"
  - git push github HEAD:master --force
  when: manual

